import React from "react";
import { Inter } from "next/font/google";
import Navbar from "@/components/common/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full h-[100vh]" lang="en" suppressHydrationWarning>
      <div className="w-full h-[100vh]">
        <div className="w-full h-[50px] bg-white px-2 sm:px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
          <Navbar />
        </div>
        <div className="w-full h-calc-100vh-minus-50 bg-slate-100 px-2 sm:px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
          {children}
        </div>
      </div>
    </main>
  );
}
