const data = {
  data: {
    backup_code_enabled: false,
    banned: false,
    create_organization_enabled: true,
    created_at: 1720245176238,
    delete_self_enabled: true,
    email_addresses: [
      {
        created_at: 1720245159744,
        email_address: "sasindudil0002@gmail.com",
        id: "idn_2irOJliAJx3Vaj61uGiubgWprWX",
        linked_to: [],
        object: "email_address",
        reserved: false,
        updated_at: 1720245176269,
        verification: {
          attempts: 1,
          expire_at: 1720245761195,
          status: "verified",
          strategy: "email_code",
        },
      },
    ],
    external_accounts: [],
    external_id: null,
    first_name: null,
    has_image: false,
    id: "user_2irOLtKYK2WCpFE3T6hfJKnKC10",
    image_url:
      "https://img.clerk.com/eyJ0eXBlIjoiZGVmYXVsdCIsImlpZCI6Imluc18yaVM2ODlyS0haV1Z3Q3UycjQ5OFQ2SDFZcmYiLCJyaWQiOiJ1c2VyXzJpck9MdEtZSzJXQ3BGRTNUNmhmSktuS0MxMCJ9",
    last_active_at: 1720245176236,
    last_name: null,
    last_sign_in_at: null,
    locked: false,
    lockout_expires_in_seconds: null,
    mfa_disabled_at: null,
    mfa_enabled_at: null,
    object: "user",
    passkeys: [],
    password_enabled: true,
    phone_numbers: [],
    primary_email_address_id: "idn_2irOJliAJx3Vaj61uGiubgWprWX",
    primary_phone_number_id: null,
    primary_web3_wallet_id: null,
    private_metadata: {},
    profile_image_url: "https://www.gravatar.com/avatar?d=mp",
    public_metadata: {},
    saml_accounts: [],
    totp_enabled: false,
    two_factor_enabled: false,
    unsafe_metadata: {},
    updated_at: 1720245176278,
    username: "sasindu",
    verification_attempts_remaining: 100,
    web3_wallets: [],
  },
  event_attributes: {
    http_request: {
      client_ip: "2402:4000:20c3:ad4:64d9:e0b7:84e6:c7e7",
      user_agent:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    },
  },
  object: "event",
  type: "user.created",
};
